-- Create dietas_pacientes table
CREATE TABLE public.dietas_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  paciente_id uuid NOT NULL,
  tipo text NOT NULL,
  data_inicio date NOT NULL,
  data_remocao date NULL,
  is_archived boolean DEFAULT false,
  volume numeric(10,2) NULL,
  vet numeric(10,2) NULL,
  pt numeric(10,2) NULL,
  th numeric(10,2) NULL,
  vet_pleno numeric(10,2) NULL,
  pt_g_dia numeric(10,2) NULL,
  vet_at numeric(8,2) GENERATED ALWAYS AS (
    CASE 
      WHEN vet_pleno IS NOT NULL AND vet_pleno > 0 
      THEN (vet::numeric / vet_pleno::numeric) * 100 
      ELSE NULL 
    END
  ) STORED,
  pt_at numeric(8,2) GENERATED ALWAYS AS (
    CASE 
      WHEN pt_g_dia IS NOT NULL AND pt_g_dia > 0 
      THEN (pt::numeric / pt_g_dia::numeric) * 100 
      ELSE NULL 
    END
  ) STORED,
  observacao text NULL,
  motivo_arquivamento text NULL,
  criado_por_id uuid NULL,
  arquivado_por_id uuid NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NULL,
  CONSTRAINT dietas_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT dietas_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_dietas_pacientes_paciente_id ON public.dietas_pacientes (paciente_id);
CREATE INDEX IF NOT EXISTS idx_dietas_pacientes_data_inicio ON public.dietas_pacientes (data_inicio);
CREATE INDEX IF NOT EXISTS idx_dietas_pacientes_is_archived ON public.dietas_pacientes (is_archived);
