-- Create medicacoes_pacientes table
CREATE TABLE public.medicacoes_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  nome_medicacao text NOT NULL,
  dosagem_valor text NOT NULL,
  unidade_medida text NOT NULL,
  data_inicio date NOT NULL,
  is_archived boolean NULL DEFAULT false,
  data_fim date NULL,
  observacao text NULL,
  CONSTRAINT medicacoes_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT medicacoes_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;
