-- ============================================================================
-- MEDICAÇÕES PACIENTES
-- ============================================================================
CREATE TABLE public.medicacoes_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  nome_medicacao text NOT NULL,
  dosagem_valor text NOT NULL,
  unidade_medida text NOT NULL,
  data_inicio date NOT NULL,
  is_archived boolean NULL DEFAULT false,
  data_fim date NULL,
  observacao text NULL,
  CONSTRAINT medicacoes_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT medicacoes_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- ============================================================================
-- DISPOSITIVOS PACIENTES
-- ============================================================================
CREATE TABLE public.dispositivos_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  tipo_dispositivo text NOT NULL,
  localizacao text NOT NULL,
  data_insercao date NOT NULL,
  data_remocao timestamp with time zone NULL,
  is_archived boolean NULL DEFAULT false,
  observacao text NULL,
  CONSTRAINT dispositivos_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT dispositivos_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- ============================================================================
-- CULTURAS PACIENTES
-- ============================================================================
CREATE TABLE public.culturas_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  local character varying(255) NOT NULL,
  microorganismo character varying(255) NOT NULL,
  data_coleta date NOT NULL,
  is_archived boolean NULL DEFAULT false,
  observacao text NULL,
  CONSTRAINT culturas_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT culturas_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- ============================================================================
-- PROCEDIMENTOS PACIENTES
-- ============================================================================
CREATE TABLE public.procedimentos_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  nome_procedimento text NOT NULL,
  data_procedimento date NOT NULL,
  nome_cirurgiao text NULL,
  notas text NULL,
  is_archived boolean NULL DEFAULT false,
  CONSTRAINT procedimentos_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT procedimentos_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- ============================================================================
-- EXAMES PACIENTES
-- ============================================================================
CREATE TABLE public.exames_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  nome_exame text NOT NULL,
  data_exame date NOT NULL,
  observacao text NULL,
  is_archived boolean NULL DEFAULT false,
  CONSTRAINT exames_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT exames_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- ============================================================================
-- DIETAS PACIENTES
-- ============================================================================
CREATE TABLE public.dietas_pacientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paciente_id uuid NOT NULL,
  tipo character varying(50) NOT NULL,
  data_inicio date NOT NULL DEFAULT CURRENT_DATE,
  volume numeric(10, 2) NULL,
  vet numeric(10, 2) NULL,
  pt numeric(10, 2) NULL,
  th numeric(10, 2) NULL,
  vet_pleno numeric(10, 2) NULL,
  pt_g_dia numeric(10, 2) NULL,
  vet_at numeric GENERATED ALWAYS AS (
    CASE
      WHEN (vet_pleno IS NOT NULL AND vet_pleno > 0) 
      THEN ((vet / vet_pleno) * 100)
      ELSE 0
    END
  ) STORED,
  pt_at numeric GENERATED ALWAYS AS (
    CASE
      WHEN (pt_g_dia IS NOT NULL AND pt_g_dia > 0) 
      THEN ((pt / pt_g_dia) * 100)
      ELSE 0
    END
  ) STORED,
  is_archived boolean NULL DEFAULT false,
  created_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  data_remocao timestamp with time zone NULL,
  observacao text NULL,
  CONSTRAINT dietas_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT dietas_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_dietas_pacientes_paciente_id ON public.dietas_pacientes USING btree (paciente_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_dietas_pacientes_data ON public.dietas_pacientes USING btree (data_inicio) TABLESPACE pg_default;
