-- Create exames_pacientes table
CREATE TABLE public.exames_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  nome_exame text NOT NULL,
  data_exame date NOT NULL,
  is_archived boolean NULL DEFAULT false,
  observacao text NULL,
  CONSTRAINT exames_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT exames_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_exames_pacientes_paciente_id ON public.exames_pacientes (paciente_id);
