-- Create dietas_pacientes table
CREATE TABLE public.dietas_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL,
  paciente_id uuid NOT NULL,
  tipo text NOT NULL,
  data_inicio date NOT NULL,
  data_remocao date NULL,
  is_archived boolean NULL DEFAULT false,
  volume numeric(10,2) NULL,
  vet numeric(10,2) NULL,
  vet_pleno numeric(10,2) NULL,
  pt numeric(10,2) NULL,
  pt_g_dia numeric(10,2) NULL,
  th numeric(10,2) NULL,
  vet_at timestamp with time zone NULL,
  pt_at timestamp with time zone NULL,
  observacao text NULL,
  CONSTRAINT dietas_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT dietas_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_dietas_pacientes_paciente_id ON public.dietas_pacientes (paciente_id);
