-- Create procedimentos_pacientes table
CREATE TABLE public.procedimentos_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  nome_procedimento text NOT NULL,
  data_procedimento date NOT NULL,
  nome_cirurgiao text NULL,
  notas text NULL,
  is_archived boolean NULL DEFAULT false,
  CONSTRAINT procedimentos_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT procedimentos_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_procedimentos_pacientes_paciente_id ON public.procedimentos_pacientes (paciente_id);
