-- Create dispositivos_pacientes table
CREATE TABLE public.dispositivos_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  tipo_dispositivo text NOT NULL,
  localizacao text NOT NULL,
  data_insercao date NOT NULL,
  data_remocao timestamp with time zone NULL,
  is_archived boolean NULL DEFAULT false,
  observacao text NULL,
  CONSTRAINT dispositivos_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT dispositivos_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;
