-- Create culturas_pacientes table
CREATE TABLE public.culturas_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  local text NOT NULL,
  microorganismo text NOT NULL,
  data_coleta date NOT NULL,
  is_archived boolean NULL DEFAULT false,
  observacao text NULL,
  CONSTRAINT culturas_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT culturas_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_culturas_pacientes_paciente_id ON public.culturas_pacientes (paciente_id);
