-- Create diurese table
CREATE TABLE public.diurese (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  patient_id uuid NOT NULL,
  volume numeric(10,2) NOT NULL,
  peso numeric(10,2) NOT NULL,
  horas integer NOT NULL,
  resultado numeric GENERATED ALWAYS AS (
    CASE
      WHEN peso > 0 AND horas > 0 THEN ((volume / (horas)::numeric) / peso)
      ELSE 0
    END
  ) STORED,
  data_registro timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT diurese_pkey PRIMARY KEY (id),
  CONSTRAINT fk_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_diurese_patient_id ON public.diurese USING btree (patient_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_diurese_data_registro ON public.diurese USING btree (data_registro DESC) TABLESPACE pg_default;
