-- Create balanco_hidrico table
CREATE TABLE public.balanco_hidrico (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  patient_id uuid NOT NULL,
  volume numeric(10,2) NOT NULL,
  peso numeric(10,2) NOT NULL,
  resultado numeric GENERATED ALWAYS AS (
    CASE
      WHEN peso > 0 THEN (volume / (peso * 10.0))
      ELSE 0
    END
  ) STORED,
  data_registro timestamp with time zone NULL DEFAULT now(),
  created_at timestamp with time zone NULL DEFAULT now(),
  created_by uuid NULL,
  CONSTRAINT balanco_hidrico_pkey PRIMARY KEY (id),
  CONSTRAINT balanco_hidrico_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT balanco_hidrico_peso_check CHECK (peso > 0)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_patient_id ON public.balanco_hidrico USING btree (patient_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_data_registro ON public.balanco_hidrico USING btree (data_registro DESC) TABLESPACE pg_default;
