-- ============================================================================
-- SCRIPT CONSOLIDADO DE TODAS AS TABELAS NECESSÁRIAS
-- Execute este script no Supabase SQL Editor
-- ============================================================================

-- ============================================================================
-- 1. CLINICAL ROUNDS SIMPLE (⭐ CRÍTICO - causa erro 406)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.clinical_rounds_simple (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  round_id uuid NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid NULL REFERENCES users(id),
  
  assessment_morning text NULL,
  assessment_morning_saved_by_name text NULL,
  assessment_morning_saved_at timestamp with time zone NULL,
  
  assessment_afternoon text NULL,
  assessment_afternoon_saved_by_name text NULL,
  assessment_afternoon_saved_at timestamp with time zone NULL,
  
  assessment_night text NULL,
  assessment_night_saved_by_name text NULL,
  assessment_night_saved_at timestamp with time zone NULL,
  
  recommendation_morning text NULL,
  recommendation_morning_saved_by_name text NULL,
  recommendation_morning_saved_at timestamp with time zone NULL,
  
  recommendation_afternoon text NULL,
  recommendation_afternoon_saved_by_name text NULL,
  recommendation_afternoon_saved_at timestamp with time zone NULL,
  
  recommendation_night text NULL,
  recommendation_night_saved_by_name text NULL,
  recommendation_night_saved_at timestamp with time zone NULL,
  
  status text NULL CHECK (status IN ('estavel', 'instavel', 'em_risco'))
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_clinical_rounds_simple_patient_id ON public.clinical_rounds_simple(patient_id);
CREATE INDEX IF NOT EXISTS idx_clinical_rounds_simple_round_id ON public.clinical_rounds_simple(round_id);
CREATE INDEX IF NOT EXISTS idx_clinical_rounds_simple_created_at ON public.clinical_rounds_simple(created_at);

-- ============================================================================
-- 2. MEDICAÇÕES PACIENTES
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.medicacoes_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
  nome_medicacao text NOT NULL,
  dosagem_valor text NOT NULL,
  unidade_medida text NOT NULL,
  data_inicio date NOT NULL,
  is_archived boolean NULL DEFAULT false,
  data_fim date NULL,
  observacao text NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_medicacoes_paciente_id ON public.medicacoes_pacientes(paciente_id);

-- ============================================================================
-- 3. DISPOSITIVOS PACIENTES
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.dispositivos_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
  tipo_dispositivo text NOT NULL,
  localizacao text NOT NULL,
  data_insercao date NOT NULL,
  data_remocao timestamp with time zone NULL,
  is_archived boolean NULL DEFAULT false,
  observacao text NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_dispositivos_paciente_id ON public.dispositivos_pacientes(paciente_id);

-- ============================================================================
-- 4. CULTURAS PACIENTES
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.culturas_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
  local character varying(255) NOT NULL,
  microorganismo character varying(255) NOT NULL,
  data_coleta date NOT NULL,
  is_archived boolean NULL DEFAULT false,
  observacao text NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_culturas_paciente_id ON public.culturas_pacientes(paciente_id);

-- ============================================================================
-- 5. PROCEDIMENTOS PACIENTES
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.procedimentos_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
  nome_procedimento text NOT NULL,
  data_procedimento date NOT NULL,
  nome_cirurgiao text NULL,
  notas text NULL,
  is_archived boolean NULL DEFAULT false
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_procedimentos_paciente_id ON public.procedimentos_pacientes(paciente_id);

-- ============================================================================
-- 6. EXAMES PACIENTES
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.exames_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
  nome_exame text NOT NULL,
  data_exame date NOT NULL,
  observacao text NULL,
  is_archived boolean NULL DEFAULT false
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_exames_paciente_id ON public.exames_pacientes(paciente_id);

-- ============================================================================
-- 7. DIETAS PACIENTES
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.dietas_pacientes (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  paciente_id uuid NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
  tipo character varying(50) NOT NULL,
  data_inicio date NOT NULL DEFAULT CURRENT_DATE,
  volume numeric(10, 2) NULL,
  vet numeric(10, 2) NULL,
  pt numeric(10, 2) NULL,
  th numeric(10, 2) NULL,
  vet_pleno numeric(10, 2) NULL,
  pt_g_dia numeric(10, 2) NULL,
  vet_at numeric GENERATED ALWAYS AS (
    CASE
      WHEN (vet_pleno IS NOT NULL AND vet_pleno > 0) 
      THEN ((vet / vet_pleno) * 100)
      ELSE 0
    END
  ) STORED,
  pt_at numeric GENERATED ALWAYS AS (
    CASE
      WHEN (pt_g_dia IS NOT NULL AND pt_g_dia > 0) 
      THEN ((pt / pt_g_dia) * 100)
      ELSE 0
    END
  ) STORED,
  is_archived boolean NULL DEFAULT false,
  created_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  data_remocao timestamp with time zone NULL,
  observacao text NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_dietas_paciente_id ON public.dietas_pacientes(paciente_id);
CREATE INDEX IF NOT EXISTS idx_dietas_data_inicio ON public.dietas_pacientes(data_inicio);

-- ============================================================================
-- 8. DIAGNÓSTICOS HISTÓRICO
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.diagnosticos_historico (
  id bigserial NOT NULL PRIMARY KEY,
  patient_id uuid NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
  pergunta_id integer NOT NULL REFERENCES perguntas_diagnistico (id) ON DELETE CASCADE,
  opcao_id integer NOT NULL REFERENCES pergunta_opcoes_diagnostico (id) ON DELETE CASCADE,
  texto_digitado text NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['resolvido'::text, 'nao_resolvido'::text])),
  created_at timestamp with time zone NULL DEFAULT now(),
  opcao_label text NULL,
  created_by uuid NULL REFERENCES users (id),
  arquivado boolean NULL DEFAULT false
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_hist_pergunta_id ON public.diagnosticos_historico(pergunta_id);
CREATE INDEX IF NOT EXISTS idx_hist_opcao_id ON public.diagnosticos_historico(opcao_id);
CREATE INDEX IF NOT EXISTS idx_diagnosticos_historico_opcao_label ON public.diagnosticos_historico(opcao_label);

-- ============================================================================
-- FIM DO SCRIPT
-- Execute tudo de uma vez no Supabase SQL Editor
-- ============================================================================
