-- ============================================================================
-- Criar tabelas de Exames e Dietas dos Pacientes
-- Execute este SQL no console do Supabase
-- ============================================================================

-- ============================================================================
-- Tabela: exames_pacientes
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.exames_pacientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paciente_id uuid NOT NULL,
  nome_exame text NOT NULL,
  data_exame date NOT NULL,
  observacao text NULL,
  is_archived boolean NULL DEFAULT false,
  CONSTRAINT exames_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT exames_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Índices para exames_pacientes
CREATE INDEX IF NOT EXISTS idx_exames_pacientes_paciente_id 
  ON public.exames_pacientes USING btree (paciente_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_exames_pacientes_data_exame 
  ON public.exames_pacientes USING btree (data_exame DESC) TABLESPACE pg_default;

-- ============================================================================
-- Tabela: dietas_pacientes
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.dietas_pacientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paciente_id uuid NOT NULL,
  tipo character varying(50) NOT NULL,
  data_inicio date NOT NULL DEFAULT CURRENT_DATE,
  volume numeric(10, 2) NULL,
  vet numeric(10, 2) NULL,
  pt numeric(10, 2) NULL,
  th numeric(10, 2) NULL,
  vet_pleno numeric(10, 2) NULL,
  pt_g_dia numeric(10, 2) NULL,
  vet_at numeric(10, 2) GENERATED ALWAYS AS (
    CASE
      WHEN (vet_pleno IS NOT NULL AND vet_pleno > 0) 
      THEN ((vet / vet_pleno) * 100)
      ELSE 0
    END
  ) STORED,
  pt_at numeric(10, 2) GENERATED ALWAYS AS (
    CASE
      WHEN (pt_g_dia IS NOT NULL AND pt_g_dia > 0) 
      THEN ((pt / pt_g_dia) * 100)
      ELSE 0
    END
  ) STORED,
  is_archived boolean NULL DEFAULT false,
  created_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  data_remocao timestamp with time zone NULL,
  observacao text NULL,
  CONSTRAINT dietas_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT dietas_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES patients (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Índices para dietas_pacientes
CREATE INDEX IF NOT EXISTS idx_dietas_pacientes_paciente_id 
  ON public.dietas_pacientes USING btree (paciente_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_dietas_pacientes_data_inicio 
  ON public.dietas_pacientes USING btree (data_inicio DESC) TABLESPACE pg_default;

-- ============================================================================
-- Habilitar RLS (Row Level Security)
-- ============================================================================
ALTER TABLE public.exames_pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dietas_pacientes ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- Políticas de acesso para exames_pacientes
-- ============================================================================
CREATE POLICY "Anon can read all exames_pacientes"
ON public.exames_pacientes FOR SELECT
TO anon
USING (true);

CREATE POLICY "Anon can insert exames_pacientes"
ON public.exames_pacientes FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "Anon can update exames_pacientes"
ON public.exames_pacientes FOR UPDATE
TO anon
USING (true);

CREATE POLICY "Anon can delete exames_pacientes"
ON public.exames_pacientes FOR DELETE
TO anon
USING (true);

-- ============================================================================
-- Políticas de acesso para dietas_pacientes
-- ============================================================================
CREATE POLICY "Anon can read all dietas_pacientes"
ON public.dietas_pacientes FOR SELECT
TO anon
USING (true);

CREATE POLICY "Anon can insert dietas_pacientes"
ON public.dietas_pacientes FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "Anon can update dietas_pacientes"
ON public.dietas_pacientes FOR UPDATE
TO anon
USING (true);

CREATE POLICY "Anon can delete dietas_pacientes"
ON public.dietas_pacientes FOR DELETE
TO anon
USING (true);

-- ============================================================================
-- Trigger para atualizar updated_at automaticamente
-- ============================================================================
CREATE OR REPLACE FUNCTION update_dietas_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_dietas_pacientes_updated_at ON dietas_pacientes;

CREATE TRIGGER update_dietas_pacientes_updated_at
BEFORE UPDATE ON dietas_pacientes
FOR EACH ROW
EXECUTE FUNCTION update_dietas_updated_at();
